# Place your local configuration in /etc/mosquitto/conf.d/
# 
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

# allow anonymous clients
allow_anonymous true

# secure open port
listener 1883

# websocket
listener 9001
protocol websockets