services:
  node-red:
    image: "nodered/node-red"
    user: root
    ports:
      - "1890:1880"
    volumes:
      - ./data:/data

  influxdb:
    image: "influxdb:1.8.3"
    ports:
      - "8090:8086"
      - "8088:8088"
    volumes:
      - "./influxdb:/etc/influxdb"
      - "influx-data:/var/lib/influxdb"
    environment:
      - INFLUXDB_BIND_ADDRESS=:8088

  grafana:
    image: "grafana/grafana"
    ports:
      - "3090:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: unless-stopped

    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=monitoring
    
    ports:
      - "5432:5432"

    volumes:
      - timescaledb-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  node-red-data:
  influx-data:
  grafana-data:
  timescaledb-data:
