services:
  node-red:
    image: "nodered/node-red"
    user: root
    ports:
      - "1890:1880"
    volumes:
      - ./data:/data
      - /home/mind/Documents/workspaces/node-red-contrib-miza:/workspace/node-red-contrib-miza
    networks:
      inet_network:
      plc_network:
        ipv4_address: 192.168.1.174

  influxdb:
    image: "influxdb:1.8.3"
    ports:
      - "8090:8086"
      - "8088:8088"
    volumes:
      - "./influxdb:/etc/influxdb"
      - "influx-data:/var/lib/influxdb"
    environment:
      - INFLUXDB_BIND_ADDRESS=:8088
    networks:
      inet_network:
      # plc_network:
      #   ipv4_address: 192.168.1.175

  grafana:
    image: "grafana/grafana"
    ports:
      - "3090:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./grafana:/etc/grafana"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3090
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_RENDERING_RENDERER_TOKEN=mind
    depends_on:
      - renderer
    networks:
      inet_network: {}

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    environment:
      - AUTH_TOKEN=mind
    networks:
      inet_network: {}

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: unless-stopped

    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=monitoring
    
    ports:
      - "5432:5432"

    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      inet_network: {}

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      inet_network: {}

networks:
  plc_network:
    driver: macvlan
    driver_opts:
      parent: enp0s31f6  # The physical interface you want to use
    ipam:
      config:
      - subnet: 192.168.1.0/24
      #     gateway: 192.168.1.1
  plc_network2:
    driver: macvlan
    driver_opts:
      parent: enx00e04c70b7bd
    ipam:
      config:
      - subnet: 192.168.0.0/24
  inet_network:
    driver: bridge
      

volumes:
  node-red-data:
  influx-data:
  grafana-data:
  timescaledb-data:
